#pragma once
// Generated by tools/generate_display_profile.py from display_profiles.json.
// Do not edit this file by hand.

#if CONFIG_USE_EMOTE_MESSAGE_STYLE
#define HENSUN_DISPLAY_PROFILE_ID "selfhosted-landscape"
#define DISPLAY_WIDTH 320
#define DISPLAY_HEIGHT 240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY true
#else
#define HENSUN_DISPLAY_PROFILE_ID "official-portrait"
#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 320
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false
#endif
