// Generated by tools/generate_face_assets.py. Do not edit.
// Source manifest SHA256: ef297b34bb0d7e33915392513b2142d5a9b47bac912bd87e2f2b4151c79693a6
#ifndef HENSUN_FACE_ASSETS_H
#define HENSUN_FACE_ASSETS_H

#include <lvgl.h>
#include <stdint.h>

#define HENSUN_FACE_SCENE_COUNT 60
#define HENSUN_FACE_SYMBOL_COUNT 36
#define HENSUN_FACE_SOURCE_MANIFEST_SHA256 "ef297b34bb0d7e33915392513b2142d5a9b47bac912bd87e2f2b4151c79693a6"

#ifdef __cplusplus
extern "C" {
#endif

LV_IMAGE_DECLARE(hensun_symbol_arrow_up);
LV_IMAGE_DECLARE(hensun_symbol_battery_charge);
LV_IMAGE_DECLARE(hensun_symbol_battery_critical);
LV_IMAGE_DECLARE(hensun_symbol_battery_done);
LV_IMAGE_DECLARE(hensun_symbol_battery_low);
LV_IMAGE_DECLARE(hensun_symbol_bell);
LV_IMAGE_DECLARE(hensun_symbol_breath);
LV_IMAGE_DECLARE(hensun_symbol_check);
LV_IMAGE_DECLARE(hensun_symbol_clock);
LV_IMAGE_DECLARE(hensun_symbol_confetti);
LV_IMAGE_DECLARE(hensun_symbol_confirm_ring);
LV_IMAGE_DECLARE(hensun_symbol_ellipsis);
LV_IMAGE_DECLARE(hensun_symbol_greeting);
LV_IMAGE_DECLARE(hensun_symbol_heart);
LV_IMAGE_DECLARE(hensun_symbol_hug);
LV_IMAGE_DECLARE(hensun_symbol_listen);
LV_IMAGE_DECLARE(hensun_symbol_meal);
LV_IMAGE_DECLARE(hensun_symbol_mic_broken);
LV_IMAGE_DECLARE(hensun_symbol_mode);
LV_IMAGE_DECLARE(hensun_symbol_moon);
LV_IMAGE_DECLARE(hensun_symbol_noise);
LV_IMAGE_DECLARE(hensun_symbol_pairing);
LV_IMAGE_DECLARE(hensun_symbol_question);
LV_IMAGE_DECLARE(hensun_symbol_search);
LV_IMAGE_DECLARE(hensun_symbol_service_busy);
LV_IMAGE_DECLARE(hensun_symbol_shield);
LV_IMAGE_DECLARE(hensun_symbol_sparkles);
LV_IMAGE_DECLARE(hensun_symbol_startup);
LV_IMAGE_DECLARE(hensun_symbol_sun);
LV_IMAGE_DECLARE(hensun_symbol_teardrop);
LV_IMAGE_DECLARE(hensun_symbol_thermometer);
LV_IMAGE_DECLARE(hensun_symbol_thought);
LV_IMAGE_DECLARE(hensun_symbol_timer_done);
LV_IMAGE_DECLARE(hensun_symbol_volume);
LV_IMAGE_DECLARE(hensun_symbol_wifi);
LV_IMAGE_DECLARE(hensun_symbol_wifi_broken);

const lv_image_dsc_t* HensunFaceSceneImageByIndex(uint8_t scene_index);
uint32_t HensunFaceSceneAccentRgbByIndex(uint8_t scene_index);

#ifdef __cplusplus
}
#endif

#endif  // HENSUN_FACE_ASSETS_H
