#!/usr/bin/env python3
"""Validate Hensun display profiles and generate the compile-time header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


BOARD = Path(__file__).resolve().parents[1]
PROFILES = BOARD / "display_profiles.json"
EMOTE_SPEC = BOARD / "emote_lab/source/hensun_emote_motion_spec.json"
OUTPUT = BOARD / "display_profile_generated.h"


def macro_bool(value: bool) -> str:
    return "true" if value else "false"


def header_for(profiles: dict[str, dict]) -> str:
    official = profiles["official-portrait"]
    emote = profiles["selfhosted-landscape"]
    return f'''#pragma once
// Generated by tools/generate_display_profile.py from display_profiles.json.
// Do not edit this file by hand.

#if CONFIG_USE_EMOTE_MESSAGE_STYLE
#define HENSUN_DISPLAY_PROFILE_ID "selfhosted-landscape"
#define DISPLAY_WIDTH {emote["logical_size"]["width"]}
#define DISPLAY_HEIGHT {emote["logical_size"]["height"]}
#define DISPLAY_MIRROR_X {macro_bool(emote["mirror_x"])}
#define DISPLAY_MIRROR_Y {macro_bool(emote["mirror_y"])}
#define DISPLAY_SWAP_XY {macro_bool(emote["swap_xy"])}
#else
#define HENSUN_DISPLAY_PROFILE_ID "official-portrait"
#define DISPLAY_WIDTH {official["logical_size"]["width"]}
#define DISPLAY_HEIGHT {official["logical_size"]["height"]}
#define DISPLAY_MIRROR_X {macro_bool(official["mirror_x"])}
#define DISPLAY_MIRROR_Y {macro_bool(official["mirror_y"])}
#define DISPLAY_SWAP_XY {macro_bool(official["swap_xy"])}
#endif
'''


def validate(profiles: dict[str, dict]) -> None:
    if set(profiles) != {"official-portrait", "selfhosted-landscape"}:
        raise SystemExit("display profiles must define official-portrait and selfhosted-landscape")
    for name, profile in profiles.items():
        size = profile.get("logical_size", {})
        if profile.get("controller") != "st7789" or size.get("width", 0) <= 0 or size.get("height", 0) <= 0:
            raise SystemExit(f"invalid display profile: {name}")
    emote = profiles["selfhosted-landscape"]
    spec = json.loads(EMOTE_SPEC.read_text(encoding="utf-8"))
    if emote.get("resource_package") != spec.get("asset_set"):
        raise SystemExit("landscape profile resource package must match the emote asset set")
    if emote["logical_size"] != {"width": spec["canvas"]["width"], "height": spec["canvas"]["height"]}:
        raise SystemExit("landscape profile dimensions must match the emote canvas")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated header is stale")
    args = parser.parse_args()
    data = json.loads(PROFILES.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise SystemExit("unsupported display profile schema version")
    profiles = data.get("profiles", {})
    validate(profiles)
    content = header_for(profiles)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit(f"generated display profile is stale: {OUTPUT}")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
