#!/usr/bin/env python3
"""Generate compact LVGL face symbols from the company expression package.

The 1536x1024 static masters are design references, not ESP32 runtime assets.
This tool calls the package's own symbol renderer, crops each reusable symbol,
and stores it as a 48x48 LVGL A4 alpha mask.  Color remains runtime-selectable.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw


BOARD_DIR = Path(__file__).resolve().parents[1]
ICON_SIZE = 48
CONTENT_SIZE = 42
PALETTE = {
    "cyan": 0x25E1E9,
    "amber": 0xFFBE46,
    "red": 0xFF5B68,
    "mint": 0x70F7CB,
    "blue": 0x5BAAFF,
    "pink": 0xFF86B7,
}
GENERATED_FILES = (
    "hensun_face_catalog.json",
    "hensun_face_assets.h",
    "hensun_face_assets.c",
)


def load_renderer(package_dir: Path):
    renderer_path = package_dir / "开发工具" / "render_expression_assets.py"
    if not renderer_path.is_file():
        raise FileNotFoundError(f"company renderer not found: {renderer_path}")
    spec = importlib.util.spec_from_file_location("hensun_company_face_renderer", renderer_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"unable to import company renderer: {renderer_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def read_manifest(package_dir: Path) -> tuple[list[dict], str]:
    path = package_dir / "expressions_manifest.json"
    raw = path.read_bytes()
    scenes = json.loads(raw.decode("utf-8"))
    digest = hashlib.sha256(raw).hexdigest()
    if len(scenes) != 60:
        raise ValueError(f"expected 60 company scenes, found {len(scenes)}")
    expected_ids = [f"{index:03d}" for index in range(1, 61)]
    actual_ids = [scene["id"] for scene in scenes]
    if actual_ids != expected_ids:
        raise ValueError("company scene IDs must be contiguous from 001 through 060")
    return scenes, digest


def render_symbol_masks(renderer, symbols: list[str]) -> dict[str, Image.Image]:
    masks: dict[str, Image.Image] = {}
    for symbol in symbols:
        canvas = Image.new("RGBA", (renderer.W, renderer.H), (0, 0, 0, 0))
        renderer.draw_symbol(canvas, symbol, accent=(255, 255, 255, 255))
        alpha = canvas.getchannel("A")
        bounds = alpha.getbbox()
        if bounds is None:
            raise ValueError(f"company renderer produced an empty symbol: {symbol}")
        cropped = alpha.crop(bounds)
        cropped.thumbnail((CONTENT_SIZE, CONTENT_SIZE), Image.Resampling.LANCZOS)
        device_mask = Image.new("L", (ICON_SIZE, ICON_SIZE), 0)
        device_mask.paste(
            cropped,
            ((ICON_SIZE - cropped.width) // 2, (ICON_SIZE - cropped.height) // 2),
        )
        masks[symbol] = device_mask
    return masks


def pack_a4(mask: Image.Image) -> bytes:
    packed = bytearray()
    pixels = mask.tobytes()
    for y in range(ICON_SIZE):
        row = pixels[y * ICON_SIZE : (y + 1) * ICON_SIZE]
        for x in range(0, ICON_SIZE, 2):
            high = min(15, (row[x] + 8) // 17)
            low = min(15, (row[x + 1] + 8) // 17)
            packed.append((high << 4) | low)
    return bytes(packed)


def c_bytes(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def build_catalog(scenes: list[dict], manifest_sha256: str) -> str:
    catalog = {
        "source": {
            "package": "HensunAI-60场景表情开发包-V1.0",
            "style_version": "HENSUN_FACE_V1.0",
            "manifest_sha256": manifest_sha256,
            "derivation": "48x48 LVGL A4 local symbol components",
        },
        "scenes": [
            {
                "id": scene["id"],
                "name": scene["name"],
                "event": scene["event"],
                "symbol": scene["visual"]["symbol"],
                "accent": scene["accent"],
                "source_asset_sha256": scene["checksum_sha256"],
            }
            for scene in scenes
        ],
    }
    return json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"


def build_header(symbols: list[str], manifest_sha256: str) -> str:
    declarations = "\n".join(
        f"LV_IMAGE_DECLARE(hensun_symbol_{symbol});" for symbol in symbols
    )
    return f"""// Generated by tools/generate_face_assets.py. Do not edit.
// Source manifest SHA256: {manifest_sha256}
#ifndef HENSUN_FACE_ASSETS_H
#define HENSUN_FACE_ASSETS_H

#include <lvgl.h>
#include <stdint.h>

#define HENSUN_FACE_SCENE_COUNT 60
#define HENSUN_FACE_SYMBOL_COUNT {len(symbols)}
#define HENSUN_FACE_SOURCE_MANIFEST_SHA256 \"{manifest_sha256}\"

#ifdef __cplusplus
extern \"C\" {{
#endif

{declarations}

const lv_image_dsc_t* HensunFaceSceneImageByIndex(uint8_t scene_index);
uint32_t HensunFaceSceneAccentRgbByIndex(uint8_t scene_index);

#ifdef __cplusplus
}}
#endif

#endif  // HENSUN_FACE_ASSETS_H
"""


def build_source(
    scenes: list[dict], symbols: list[str], masks: dict[str, Image.Image], manifest_sha256: str
) -> str:
    definitions = []
    for symbol in symbols:
        packed = pack_a4(masks[symbol])
        definitions.append(
            f"""static const uint8_t hensun_symbol_{symbol}_map[] = {{
{c_bytes(packed)}
}};

const lv_image_dsc_t hensun_symbol_{symbol} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_A4,
        .flags = 0,
        .w = {ICON_SIZE},
        .h = {ICON_SIZE},
        .stride = {ICON_SIZE // 2},
        .reserved_2 = 0,
    }},
    .data_size = sizeof(hensun_symbol_{symbol}_map),
    .data = hensun_symbol_{symbol}_map,
    .reserved = NULL,
    .reserved_2 = NULL,
}};"""
        )

    scene_images = []
    scene_accents = []
    for scene in scenes:
        symbol = scene["visual"]["symbol"]
        scene_images.append("NULL" if symbol == "none" else f"&hensun_symbol_{symbol}")
        accent = scene["accent"]
        if accent not in PALETTE:
            raise ValueError(f"unsupported accent {accent!r} in scene {scene['id']}")
        scene_accents.append(f"0x{PALETTE[accent]:06X}u")

    image_rows = "\n".join(
        "    " + ", ".join(scene_images[offset : offset + 4]) + ","
        for offset in range(0, len(scene_images), 4)
    )
    accent_rows = "\n".join(
        "    " + ", ".join(scene_accents[offset : offset + 6]) + ","
        for offset in range(0, len(scene_accents), 6)
    )
    return f"""// Generated by tools/generate_face_assets.py. Do not edit.
// Source manifest SHA256: {manifest_sha256}
#include \"hensun_face_assets.h\"

#include <stddef.h>

{"\n\n".join(definitions)}

static const lv_image_dsc_t* const kHensunSceneImages[HENSUN_FACE_SCENE_COUNT] = {{
{image_rows}
}};

static const uint32_t kHensunSceneAccents[HENSUN_FACE_SCENE_COUNT] = {{
{accent_rows}
}};

const lv_image_dsc_t* HensunFaceSceneImageByIndex(uint8_t scene_index) {{
    return scene_index < HENSUN_FACE_SCENE_COUNT ? kHensunSceneImages[scene_index] : NULL;
}}

uint32_t HensunFaceSceneAccentRgbByIndex(uint8_t scene_index) {{
    return scene_index < HENSUN_FACE_SCENE_COUNT ? kHensunSceneAccents[scene_index] : 0x25E1E9u;
}}
"""


def build_outputs(package_dir: Path) -> tuple[dict[str, str], dict[str, Image.Image]]:
    scenes, manifest_sha256 = read_manifest(package_dir)
    symbols = sorted(
        {scene["visual"]["symbol"] for scene in scenes if scene["visual"]["symbol"] != "none"}
    )
    renderer = load_renderer(package_dir)
    masks = render_symbol_masks(renderer, symbols)
    outputs = {
        "hensun_face_catalog.json": build_catalog(scenes, manifest_sha256),
        "hensun_face_assets.h": build_header(symbols, manifest_sha256),
        "hensun_face_assets.c": build_source(scenes, symbols, masks, manifest_sha256),
    }
    return outputs, masks


def write_preview(path: Path, masks: dict[str, Image.Image]) -> None:
    columns = 6
    cell_w, cell_h = 112, 82
    rows = math.ceil(len(masks) / columns)
    sheet = Image.new("RGB", (columns * cell_w, rows * cell_h), (2, 8, 17))
    draw = ImageDraw.Draw(sheet)
    for index, (name, mask) in enumerate(masks.items()):
        x = (index % columns) * cell_w
        y = (index // columns) * cell_h
        icon = Image.new("RGBA", mask.size, (73, 246, 255, 0))
        icon.putalpha(mask)
        sheet.paste(icon, (x + 32, y + 4), icon)
        draw.text((x + 4, y + 57), name, fill=(215, 252, 255))
    path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-package", required=True, type=Path)
    parser.add_argument("--output-dir", type=Path, default=BOARD_DIR)
    parser.add_argument("--preview", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    outputs, masks = build_outputs(args.source_package.resolve())
    if args.check:
        mismatches = [
            name
            for name, expected in outputs.items()
            if not (args.output_dir / name).is_file()
            or (args.output_dir / name).read_text(encoding="utf-8") != expected
        ]
        if mismatches:
            print("generated assets are stale: " + ", ".join(mismatches), file=sys.stderr)
            return 1
        print(f"PASS: {len(outputs)} files match the 60-scene company source")
    else:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        for name, content in outputs.items():
            (args.output_dir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"Generated {len(outputs)} files with {len(masks)} reusable symbols")

    if args.preview:
        write_preview(args.preview, masks)
        print(f"Preview: {args.preview}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
