from __future__ import annotations

import argparse
import json
from pathlib import Path
from pprint import pformat
from textwrap import indent
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CONFIG_SOURCES = sorted(
    (ROOT / "contracts/device-config").glob("v*/schema.json"),
    key=lambda path: int(path.parent.name.removeprefix("v")),
)
WS_SOURCE = ROOT / "contracts/device-ws/v1/messages.json"

OUTPUTS = {
    "python": ROOT / "backend/generated/device_contracts.py",
    "cpp": ROOT / "firmware/xiaozhi-esp32/main/generated/device_contracts_v1.h",
    "typescript": ROOT / "web/lib/generated/device-contracts.ts",
    "ws_samples": ROOT / "contracts/generated/device-ws-v1.samples.json",
}


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _identifier(key: str) -> str:
    return key.upper().replace(".", "_").replace("-", "_")


def _member_name(key: str) -> str:
    return key.lower().replace(".", "_").replace("-", "_")


def _python(configs: list[dict[str, Any]], ws: dict[str, Any]) -> str:
    config = configs[-1]
    fields = {item["key"]: item for item in config["fields"]}
    schemas = {
        item["schema_version"]: {field["key"]: field for field in item["fields"]}
        for item in configs
    }
    message_types = indent(
        pformat(tuple(ws["message_types"]), width=72, sort_dicts=False), "    "
    )
    field_catalog = indent(pformat(fields, width=72, sort_dicts=False), "    ")
    schema_catalog = indent(pformat(schemas, width=72, sort_dicts=False), "    ")
    return f'''# Generated by scripts/generate_contracts.py. Do not edit.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

DEVICE_CONFIG_SCHEMA_VERSION = {config["schema_version"]}
DEVICE_WS_PROTOCOL_VERSION = {ws["protocol_version"]}
DEVICE_WS_MESSAGE_TYPES = frozenset(
{message_types}
)
DEVICE_CONFIG_FIELDS: dict[str, dict[str, Any]] = (
{field_catalog}
)
DEVICE_CONFIG_SCHEMAS: dict[int, dict[str, dict[str, Any]]] = (
{schema_catalog}
)


def device_config_fields(
    schema_version: int = DEVICE_CONFIG_SCHEMA_VERSION,
) -> dict[str, dict[str, Any]]:
    try:
        return DEVICE_CONFIG_SCHEMAS[schema_version]
    except KeyError as exc:
        raise ValueError(
            f"unsupported device configuration schema version: {{schema_version}}"
        ) from exc


def default_device_config(
    schema_version: int = DEVICE_CONFIG_SCHEMA_VERSION,
) -> dict[str, int | str]:
    return {{key: spec["default"] for key, spec in device_config_fields(schema_version).items()}}


def validate_device_config(
    values: Mapping[str, object], *, allowed_permissions: set[str] | None = None,
    schema_version: int = DEVICE_CONFIG_SCHEMA_VERSION,
) -> dict[str, int | str]:
    validated: dict[str, int | str] = {{}}
    fields = device_config_fields(schema_version)
    for key, value in values.items():
        spec = fields.get(key)
        if spec is None:
            raise ValueError(f"unknown configuration field: {{key}}")
        if allowed_permissions is not None and spec["permission"] not in allowed_permissions:
            raise PermissionError(f"configuration field is not permitted: {{key}}")
        if spec["type"] == "integer":
            if not isinstance(value, int) or isinstance(value, bool):
                raise ValueError(f"configuration field must be an integer: {{key}}")
            if value < spec["minimum"] or value > spec["maximum"]:
                raise ValueError(f"configuration field is outside its range: {{key}}")
        elif spec["type"] == "string":
            if not isinstance(value, str) or value not in spec["enum"]:
                raise ValueError(f"configuration field has an invalid option: {{key}}")
        validated[key] = cast(int | str, value)
    return validated
'''


def _cpp(config: dict[str, Any], ws: dict[str, Any]) -> str:
    lines = [
        "// Generated by scripts/generate_contracts.py. Do not edit.",
        "#pragma once",
        "",
        "#include <string>",
        "",
        f"#define HENSUN_DEVICE_CONFIG_SCHEMA_VERSION {config['schema_version']}",
        f"#define HENSUN_DEVICE_WS_PROTOCOL_VERSION {ws['protocol_version']}",
        "",
    ]
    for item in config["fields"]:
        name = _identifier(item["key"])
        lines.append(f'#define HENSUN_CONFIG_KEY_{name} "{item["key"]}"')
        default = item["default"]
        if isinstance(default, str):
            lines.append(f'#define HENSUN_CONFIG_DEFAULT_{name} "{default}"')
        else:
            lines.append(f"#define HENSUN_CONFIG_DEFAULT_{name} {default}")
        if item["type"] == "integer":
            lines.append(f"#define HENSUN_CONFIG_MIN_{name} {item['minimum']}")
            lines.append(f"#define HENSUN_CONFIG_MAX_{name} {item['maximum']}")
        lines.append("")
    for message_type in ws["message_types"]:
        lines.append(
            f'#define HENSUN_WS_TYPE_{_identifier(message_type)} "{message_type}"'
        )
    lines.append("")
    lines.append("struct HensunDeviceConfigValues {")
    for item in config["fields"]:
        cpp_type = "int" if item["type"] == "integer" else "std::string"
        default = item["default"]
        rendered_default = f'"{default}"' if isinstance(default, str) else str(default)
        lines.append(
            f"    {cpp_type} {_member_name(item['key'])} = {rendered_default};"
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _typescript(config: dict[str, Any], ws: dict[str, Any]) -> str:
    fields = json.dumps(config["fields"], ensure_ascii=False, indent=2)
    message_types = " | ".join(f'"{item}"' for item in ws["message_types"])
    return f'''// Generated by scripts/generate_contracts.py. Do not edit.
export const DEVICE_CONFIG_SCHEMA_VERSION = {config["schema_version"]} as const;
export const DEVICE_WS_PROTOCOL_VERSION = {ws["protocol_version"]} as const;
export type DeviceWsMessageType = {message_types};
export type DeviceConfigValue = number | string;
export type DeviceConfigPermission = "customer" | "engineering";
export type DeviceConfigApplyMode = "immediate" | "next_reply" | "next_boot";
export type DeviceConfigField = {{
  key: string;
  type: "integer" | "string";
  minimum?: number;
  maximum?: number;
  enum?: string[];
  default: DeviceConfigValue;
  permission: DeviceConfigPermission;
  apply: DeviceConfigApplyMode;
  label: string;
}};
export const DEVICE_CONFIG_FIELDS = {fields} as const satisfies readonly DeviceConfigField[];
'''


def render() -> dict[str, str]:
    configs = [_load(path) for path in CONFIG_SOURCES]
    if not configs:
        raise SystemExit("No device configuration schemas found")
    config = configs[-1]
    ws = _load(WS_SOURCE)
    rendered = {
        "python": _python(configs, ws),
        "cpp": _cpp(config, ws),
        "typescript": _typescript(config, ws),
        "ws_samples": json.dumps(ws["samples"], ensure_ascii=False, indent=2) + "\n",
    }
    for schema in configs:
        schema_defaults = {item["key"]: item["default"] for item in schema["fields"]}
        name = f"config_example_v{schema['schema_version']}"
        OUTPUTS[name] = ROOT / (
            f"contracts/generated/device-config-v{schema['schema_version']}.example.json"
        )
        rendered[name] = json.dumps(
            {"schema_version": schema["schema_version"], "values": schema_defaults},
            ensure_ascii=False,
            indent=2,
        ) + "\n"
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    stale: list[str] = []
    for name, output in OUTPUTS.items():
        expected = rendered[name]
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != expected:
                stale.append(str(output.relative_to(ROOT)))
            continue
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(expected, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Generated contracts are stale: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
